name: my_auth
description: "A new Flutter project with Firebase integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Essential dependencies
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  provider: ^6.1.5

  # Firebase dependencies
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  animated_text_kit: ^4.2.2

  # Additional utilities
  image_picker: ^1.1.2
  lottie: ^3.1.0

  # OpenStreetMap + location packages (Free alternative to Google Maps)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  http: ^1.2.1

  # Google Maps (Optional, if you still want it)
  google_maps_flutter: ^2.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
