// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCohvLhOHTwzpKuvxakpSHHmV1jFQHqQf0',
    appId: '1:299131612586:web:d374fb9afca33a7b200fd3',
    messagingSenderId: '299131612586',
    projectId: 'auth999-d76d6',
    authDomain: 'auth999-d76d6.firebaseapp.com',
    storageBucket: 'auth999-d76d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb5_kqaXqau26ZXeI7juvd7D_6eTPChRg',
    appId: '1:299131612586:android:f2542f2a487f52bf200fd3',
    messagingSenderId: '299131612586',
    projectId: 'auth999-d76d6',
    storageBucket: 'auth999-d76d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7tHCUb0-ht3S7usiUjzFQbk87DmzOVdU',
    appId: '1:299131612586:ios:368b751f361f0f03200fd3',
    messagingSenderId: '299131612586',
    projectId: 'auth999-d76d6',
    storageBucket: 'auth999-d76d6.firebasestorage.app',
    iosClientId: '299131612586-51cthtkplccli8v76r2j6k6ljkkkv8an.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7tHCUb0-ht3S7usiUjzFQbk87DmzOVdU',
    appId: '1:299131612586:ios:368b751f361f0f03200fd3',
    messagingSenderId: '299131612586',
    projectId: 'auth999-d76d6',
    storageBucket: 'auth999-d76d6.firebasestorage.app',
    iosClientId: '299131612586-51cthtkplccli8v76r2j6k6ljkkkv8an.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCohvLhOHTwzpKuvxakpSHHmV1jFQHqQf0',
    appId: '1:299131612586:web:137b93d0433217ce200fd3',
    messagingSenderId: '299131612586',
    projectId: 'auth999-d76d6',
    authDomain: 'auth999-d76d6.firebaseapp.com',
    storageBucket: 'auth999-d76d6.firebasestorage.app',
  );

}